/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lanchonetepeixinhodourado;
import cardapio.Pizza;
import pedidos.Item;
import pedidos.Pedido;
/**
 *
 * @author yaran
 */
public class Pizza_FazerPedido extends javax.swing.JFrame {

    /**
     * Creates new form F
     */
    Pedido pedidoteste;
    
    public Pizza_FazerPedido(Pedido pedidoteste) {
        initComponents();
        this.pedidoteste = pedidoteste;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qtdPizzaCalabresa = new javax.swing.JSpinner();
        qtdPizzaMussarela = new javax.swing.JSpinner();
        qtdPizzaPortuguesa = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        booleanBorda = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(673, 422));
        setResizable(false);
        setSize(new java.awt.Dimension(673, 422));
        getContentPane().setLayout(null);
        getContentPane().add(qtdPizzaCalabresa);
        qtdPizzaCalabresa.setBounds(60, 60, 60, 30);
        getContentPane().add(qtdPizzaMussarela);
        qtdPizzaMussarela.setBounds(60, 130, 60, 30);
        getContentPane().add(qtdPizzaPortuguesa);
        qtdPizzaPortuguesa.setBounds(60, 200, 60, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pizza de Portuguesa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 200, 130, 20);

        booleanBorda.setText("Borda");
        booleanBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booleanBordaActionPerformed(evt);
            }
        });
        getContentPane().add(booleanBorda);
        booleanBorda.setBounds(60, 270, 110, 20);

        jButton1.setBackground(new java.awt.Color(255, 205, 176));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 320, 148, 35);

        jButton2.setBackground(new java.awt.Color(255, 205, 176));
        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 320, 148, 35);

        jPanel1.setBackground(new java.awt.Color(217, 225, 248));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Pizza de Calabresa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pizza de Mussarela");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booleanBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booleanBordaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booleanBordaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int qtdPizzaCal = Integer.parseInt(qtdPizzaCalabresa.getValue().toString());
        int qtdPizzaMuss = Integer.parseInt(qtdPizzaMussarela.getValue().toString());
        int qtdPizzaPort = Integer.parseInt(qtdPizzaPortuguesa.getValue().toString());


        while (qtdPizzaCal>0){
            if (booleanBorda.isSelected()){
                qtdPizzaCal = qtdPizzaCal - 1;
                Pizza pizzaCal= new Pizza("calabresa",true); 
                Item pizzacal = new Item(pizzaCal);
                this.pedidoteste.addItem(pizzacal);
            }
            else{
                qtdPizzaCal = qtdPizzaCal - 1;
                Pizza pizzaCal= new Pizza("calabresa",false); 
                Item pizzacal =new Item(pizzaCal);
                this.pedidoteste.addItem(pizzacal);
            }
        }
        while (qtdPizzaMuss>0){
            if (booleanBorda.isSelected()){
                qtdPizzaMuss = qtdPizzaMuss - 1;
                Pizza PizzaMuss= new Pizza("Mussarela",true); 
                Item Pizzamuss = new Item(PizzaMuss);
                this.pedidoteste.addItem(Pizzamuss);
            }
            else{
                qtdPizzaMuss = qtdPizzaMuss - 1;
                Pizza PizzaMuss= new Pizza("Mussarela",false); 
                Item Pizzamuss =new Item(PizzaMuss);
                this.pedidoteste.addItem(Pizzamuss);
            }   
        }  
        while (qtdPizzaPort>0){
            if (booleanBorda.isSelected()){
                qtdPizzaPort = qtdPizzaPort - 1;
                Pizza PizzaPort= new Pizza("portuguesa",true); 
                Item Pizzaport = new Item(PizzaPort);
                this.pedidoteste.addItem(Pizzaport);
            }
            else{
                qtdPizzaPort = qtdPizzaPort - 1;
                Pizza PizzaPort= new Pizza("portuguesa",false); 
                Item Pizzaport =new Item(PizzaPort);
                this.pedidoteste.addItem(Pizzaport);
            }
        }
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                this.setVisible(true);
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton booleanBorda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner qtdPizzaCalabresa;
    private javax.swing.JSpinner qtdPizzaMussarela;
    private javax.swing.JSpinner qtdPizzaPortuguesa;
    // End of variables declaration//GEN-END:variables
}
