/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lanchonetepeixinhodourado;

import cardapio.Salgado;
import pedidos.Item;
import pedidos.Pedido;
/**
 *
 * @author yaran
 */
public class Salgado_FazerPedido extends javax.swing.JFrame {

    /**
     * Creates new form Salgado_FazerPedido
     */
    Pedido pedidoteste;
    
    public Salgado_FazerPedido(Pedido pedidoteste) {
        initComponents();
        this.pedidoteste = pedidoteste;
    }

    public Salgado_FazerPedido() {
        initComponents();
        this.pedidoteste = pedidoteste;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner4 = new javax.swing.JSpinner();
        jRadioButton1 = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(673, 422));
        setResizable(false);
        setSize(new java.awt.Dimension(673, 422));
        getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Frito");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(59, 41, 70, 20);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(60, 250, 60, 30);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(60, 180, 60, 30);
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(60, 110, 60, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Coxinha de Frango");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 110, 170, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Jacaré");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 180, 110, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Enrolado de salsicha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 260, 200, 20);

        jButton1.setBackground(new java.awt.Color(255, 205, 176));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 310, 148, 35);

        jButton2.setBackground(new java.awt.Color(255, 205, 176));
        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 310, 148, 35);

        jPanel1.setBackground(new java.awt.Color(217, 225, 248));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Assado");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jRadioButton2)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int qntdSalsicha = Integer.parseInt(jSpinner1.getValue().toString());
        int qntdJacare = Integer.parseInt(jSpinner2.getValue().toString());
        int qntdCoxinhaDeFrango = Integer.parseInt(jSpinner3.getValue().toString());
        
        
        while (qntdSalsicha >= 1){
            qntdSalsicha = qntdSalsicha -1;
            if (jRadioButton1.isSelected()){
                qntdSalsicha = qntdSalsicha - 1;
                Salgado salsichx = new Salgado("Enroladinho de Salsicha","Frito"); 
                Item salsicha = new Item(salsichx);
                this.pedidoteste.addItem(salsicha);        
            }
            if (jRadioButton2.isSelected()){
                qntdSalsicha = qntdSalsicha - 1;
                Salgado salsichx = new Salgado("Enroladinho de Salsicha","Assado"); 
                Item salsicha = new Item(salsichx);
                this.pedidoteste.addItem(salsicha);        
            }        
        }
        
        while (qntdJacare >= 1){
            qntdJacare = qntdJacare - 1;
            if (jRadioButton1.isSelected()){
                qntdJacare = qntdJacare - 1;
                Salgado jacarx = new Salgado("Jacare","Frito"); 
                Item jacare = new Item(jacarx);
                this.pedidoteste.addItem(jacare);        
            }
            if (jRadioButton2.isSelected()){
                qntdJacare = qntdJacare - 1;
                Salgado jacarx = new Salgado("Jacare","Assado"); 
                Item jacare = new Item(jacarx);
                this.pedidoteste.addItem(jacare);         
            }        
        }

        while (qntdCoxinhaDeFrango >= 1){
            qntdCoxinhaDeFrango = qntdCoxinhaDeFrango - 1;
            if (jRadioButton1.isSelected()){
                qntdCoxinhaDeFrango = qntdCoxinhaDeFrango - 1;
                Salgado coxinhaDeFrango = new Salgado("Coxinha de frango","Frito"); 
                Item coxinha = new Item(coxinhaDeFrango);
                this.pedidoteste.addItem(coxinha);        
            }
            if (jRadioButton2.isSelected()){
                qntdCoxinhaDeFrango = qntdCoxinhaDeFrango - 1;
                Salgado coxinhaDeFrango = new Salgado("Coxinha de frango","Assado"); 
                Item coxinha = new Item(coxinhaDeFrango);
                this.pedidoteste.addItem(coxinha);            
            }        
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salgado_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salgado_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salgado_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salgado_FazerPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salgado_FazerPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    // End of variables declaration//GEN-END:variables
}
